#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

npm run lint:js && npm run lint:sass
if ! lsof -i:6006 >/dev/null 2>&1; then
  npm run storybook &
  npx cypress run --headless
else
  npx cypress run --headless
fi
